### ISSUE TITLE
API Error on web interface

### ISSUE THREAD

**Issue by phil9309** [Ravinou/borgwarehouse#254]
Hi, I have Borgwarehouse running in an LXC Container on Proxmox, so far so good, everything was working fine.

After Troubleshooting another Container (with a few node reboots inbetween) I suddenly get "API Errror" in the web interface after login. The Borgwarehouse.service is running, backups work like expected, the repo is connected, idk where to start. can you point me where to start Troubleshooting?

**Comment by Ravinou** [comment]
Hi @phil9309 , can you send me the log ? You have a volume name "logs" and "borgwarehouse.log" inside will contain the API error normally. **Be carefull to anonymize the log if needed.**

**Comment by Ravinou** [comment]
Any news @phil9309 ?

**Comment by Ravinou** [comment]
Feel free to re-open it if needed 😊

**Comment by RudolfRendier** [comment]
Not sure if this is the same error, but my setup has the same error and is similar. (also Debian LXC on Proxmox)
Noticed this issue after a few reboots of the host, due to issues with an unrelated VM.

Log is full of this:
```Aug 17 10:48:01 borgserver npm[390]: SyntaxError: Expected ',' or ']' after array element in JSON at position 5873
Aug 17 10:48:01 borgserver npm[390]:     at JSON.parse (<anonymous>)
Aug 17 10:48:01 borgserver npm[390]:     at d (/home/borgwarehouse/app/.next/server/pages/api/cronjob/getStorageUsed.js:1:1066)
Aug 17 10:48:01 borgserver npm[390]:     at async K (/home/borgwarehouse/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
Aug 17 10:48:01 borgserver npm[390]:     at async U.render (/home/borgwarehouse/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
Aug 17 10:48:01 borgserver npm[390]:     at async NextNodeServer.runApi (/home/borgwarehouse/app/node_modules/next/dist/server/next-server.js:554:9)
Aug 17 10:48:01 borgserver npm[390]:     at async NextNodeServer.handleCatchallRenderRequest (/home/borgwarehouse/app/node_modules/next/dist/server/next-server.js:266:37)
Aug 17 10:48:01 borgserver npm[390]:     at async NextNodeServer.handleRequestImpl (/home/borgwarehouse/app/node_modules/next/dist/server/base-server.js:791:17)
Aug 17 10:48:01 borgserver npm[390]:     at async invokeRender (/home/borgwarehouse/app/node_modules/next/dist/server/lib/router-server.js:174:21)
Aug 17 10:48:01 borgserver npm[390]:     at async handleRequest (/home/borgwarehouse/app/node_modules/next/dist/server/lib/router-server.js:353:24)
Aug 17 10:48:01 borgserver npm[390]:     at async requestHandlerImpl (/home/borgwarehouse/app/node_modules/next/dist/server/lib/router-server.js:377:13)
Aug 17 10:49:01 borgserver npm[390]: SyntaxError: Expected ',' or ']' after array element in JSON at position 5873
Aug 17 10:49:01 borgserver npm[390]:     at JSON.parse (<anonymous>)
Aug 17 10:49:01 borgserver npm[390]:     at d (/home/borgwarehouse/app/.next/server/pages/api/cronjob/getStorageUsed.js:1:1066)
Aug 17 10:49:01 borgserver npm[390]:     at async K (/home/borgwarehouse/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
Aug 17 10:49:01 borgserver npm[390]:     at async U.render (/home/borgwarehouse/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
Aug 17 10:49:01 borgserver npm[390]:     at async NextNodeServer.runApi (/home/borgwarehouse/app/node_modules/next/dist/server/next-server.js:554:9)
Aug 17 10:49:01 borgserver npm[390]:     at async NextNodeServer.handleCatchallRenderRequest (/home/borgwarehouse/app/node_modules/next/dist/server/next-server.js:266:37)
Aug 17 10:49:01 borgserver npm[390]:     at async NextNodeServer.handleRequestImpl (/home/borgwarehouse/app/node_modules/next/dist/server/base-server.js:791:17)
Aug 17 10:49:01 borgserver npm[390]:     at async invokeRender (/home/borgwarehouse/app/node_modules/next/dist/server/lib/router-server.js:174:21)
```

Since it was complaining about invalid .json I checked the configs, located in /home/borgwarehouse/app/config/*
For me, the repos.json was missing the closing square bracket ], making it invalid json.

Adding that made the problem go away.

**Comment by Haringstad** [comment]
I want to reopen this issue, due to similar issue:

Application error: a client-side exception has occurred (see the browser console for more information).

Where the repo.json is containing additional bracket at the end of the file: `Mode":false}]]`

Most of the time it is only an additional bracket ']'
Sometimes it is way more information added.
