### ISSUE TITLE
Mail without authentication

### ISSUE THREAD

**Issue by ToeiRei** [Ravinou/borgwarehouse#364]
Hi there,

I am running an internal mail server here for servers that just send logs and notifications. Would it be possible to just have something like MAIL_SMTP_AUTH to none to just send it out?

**Comment by Ravinou** [comment]
Hi 👋
Do you try to just leave empty MAIL_SMTP_LOGIN and MAIL_SMTP_PWD ?

**Comment by ToeiRei** [comment]
I did not set it and the log just complains about missing login/pwd

```
2024-12-07T17:05:27.689436+01:00 BorgWarehouse Error: Missing credentials for "PLAIN"
2024-12-07T17:05:27.689491+01:00 BorgWarehouse     at SMTPConnection._formatError (/home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-connection/index.js:807:19)
2024-12-07T17:05:27.689496+01:00 BorgWarehouse     at SMTPConnection.login (/home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-connection/index.js:452:38)
2024-12-07T17:05:27.689638+01:00 BorgWarehouse     at /home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-transport/index.js:272:32
2024-12-07T17:05:27.689645+01:00 BorgWarehouse     at SMTPConnection.<anonymous> (/home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-connection/index.js:215:17)
2024-12-07T17:05:27.689655+01:00 BorgWarehouse     at Object.onceWrapper (node:events:632:28)
2024-12-07T17:05:27.689658+01:00 BorgWarehouse     at SMTPConnection.emit (node:events:518:28)
2024-12-07T17:05:27.689667+01:00 BorgWarehouse     at SMTPConnection._actionEHLO (/home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-connection/index.js:1369:14)
2024-12-07T17:05:27.689671+01:00 BorgWarehouse     at SMTPConnection._processResponse (/home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-connection/index.js:991:20)
2024-12-07T17:05:27.689680+01:00 BorgWarehouse     at SMTPConnection._onData (/home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-connection/index.js:772:14)
2024-12-07T17:05:27.689684+01:00 BorgWarehouse     at SMTPConnection._onSocketData (/home/borgwarehouse/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44) {
2024-12-07T17:05:27.689692+01:00 BorgWarehouse   code: 'EAUTH',
2024-12-07T17:05:27.689694+01:00 BorgWarehouse   command: 'API'
2024-12-07T17:05:27.689701+01:00 BorgWarehouse }
```

**Comment by Ravinou** [comment]
I'm going to set up a local mail server to make this possible. It doesn't have to be very complex.

**Comment by ToeiRei** [comment]
I suspect you're using Nodemailer and therefor could use something like a custom auth that doesn't send user authentication details?

**Comment by Ravinou** [comment]
Yes, it's nodemailer.

**Comment by rtim75** [comment]
I'd also be interested in this functionality. google smtp-relay allows to whitelist IP addresses that can send mail, and thus we don't really require authentication to send notifications and alerts from a multitude of different services.

**Comment by Ravinou** [comment]
Please, tell me if v2.4.3 solve your problem. Thank you

**Comment by ToeiRei** [comment]
We're still at `An error occurred while sending the email: Error: Missing credentials for "PLAIN"`

**Comment by Ravinou** [comment]
Yesterday, I mount a docker-mailserver and I everything works without login/pass. So I guess the context is different. Could you help me to be in the same context as you? Which provider or smtp do you use to do this? Google smtp relay obviously requires a business account, I don't have that...

**Comment by ToeiRei** [comment]
I use a local postfix server with no authentication for local networks.

**Comment by Ravinou** [comment]
@ToeiRei Please, test v2.4.4

**Comment by ToeiRei** [comment]
test successful. Thanks!
